#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DevTalkMobile.Droid.Resource", IsApplication=true)]

namespace DevTalkMobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::DevTalkMobile.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::DevTalkMobile.Droid.Resource.String.Hello;
			global::ModernHttpClient.Resource.String.library_name = global::DevTalkMobile.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int chat = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int devtalksplashscreen = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fb = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int home = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_pause = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_play = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_share = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_stop = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int itunes = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int newsletter = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int podcast = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int rss = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int slideout = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int social = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int twitter = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030002
			public const int ApplicationName = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int Hello = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
